### ISSUE TITLE
pypy Travis job failing

### ISSUE THREAD

**Issue by jayvdb** [gazpachoking/jsonref#11]
I just now set up a build on Travis, and the pypy job is reporting two errors.

They are the same two errors that appeared on the last official build (#81) at year ago:
https://travis-ci.org/gazpachoking/jsonref/jobs/13109024

It is very unlikely that the commit (0ad88d1f3) caused it, so something else changed between May 2013 and Jan 2015 .  Probably pypy changed something.

**Comment by gazpachoking** [comment]
I think some of the proxy stuff wasn't always consistent on certain python versions, it seems to be working fine on recent versions though. I did have trouble with the tests on pypy with my latest update, and haven't had time to troubleshoot. Anybody PRs to add pypy support back in would be appriciated.
