### ISSUE TITLE
JsonRef.replace_refs mocking issue

### ISSUE THREAD

**Issue by mbiokyle29** [gazpachoking/jsonref#22]
I have had quite a bit of trouble using a mock on `JsonRef.replace_refs` for testing my application which uses it. 

Here is an example:
```python
@patch.object(JsonRef, "replace_refs")
def test_mock(self, mocked_replace_refs):
        reffed_json = {"foo": {"$ref": "#bar/baz"}, "bar": {"baz": "bar"}}
        dereffed_json = {"foo": "bar", "bar": {"baz": "bar"}}
        mocked_replace_refs.return_value = dereffed_promo

       code_calling_replace_refs(reffed_json)
```

This the error I get:
```
    @wraps(method)
    def wrapper(self, *args, **kwargs):
>       notproxied = _oga(self, "__notproxied__")
E       AttributeError: 'dict' object has no attribute '__notproxied__'
```

I think it has to do with the `JsonRef` class being a proxy and some interaction with that and `@classmethod`. The easy fix is to just make `replace_refs` a free floating function (I'd be happy to make a PR with that change) but I suspect there is a better solution? Lastly, thanks for your work on this library, I have been using it quite a bit and it's 👍.

**Comment by gazpachoking** [comment]
replace_refs is just a regular function in 1.0.0

**Comment by mbiokyle29** [comment]
Thanks!
