### ISSUE TITLE
jsonref vs jsonref-ap on PyPI

### ISSUE THREAD

**Issue by vitaly-krugl** [gazpachoking/jsonref#24]
I am seeing two packages on pypi that both claim to be jsonref. I don't know which one is authentic. These are:
* https://pypi.org/project/jsonref/ (Last released: May 17, 2013)
* https://pypi.org/project/jsonref-ap/ (Last released: Mar 30, 2016)

The change in package name throws me off. Is the more recently-released one (2016) authentic?

**Comment by gazpachoking** [comment]
I did not release jsonref-ap, looks like a custom fork to me.

**Comment by gazpachoking** [comment]
I sent a note to @jacobh (I'm thinking he's the maintainer of the alternate pypi release) to see if he can switch the links to point to his fork instead of back here.
