### ISSUE TITLE
How to save to regular JSON without ref?

### ISSUE THREAD

**Issue by vlad-stack** [gazpachoking/jsonref#41]
Hey,

I'm trying to convert JSON from a file with ref into a file without ref. Is it any way to do so?

**Comment by vconrado** [comment]
You can use deepcopy. I found this solution in this  [comment](https://github.com/gazpachoking/jsonref/issues/9#issuecomment-236618843).

**Comment by gazpachoking** [comment]
proxy mode can be disabled on 1.0.0
