### ISSUE TITLE
Disabling proxies doesn't work recursively

### ISSUE THREAD

**Issue by plondino** [gazpachoking/jsonref#48]
When set `proxies=False`, the `$ref` fields in the first document are converted to a regular dict, but if there is a `$ref` in the resolved document, it remains a jsonref proxy and the document won't serialize via vanilla `json.dumps`.

**Comment by plondino** [comment]
Here's a short script and files that reproduce the issue:

```
import json
import os
import pathlib
import sys
from typing import Union

import jsonref

PathLike = Union[str, bytes, os.PathLike]

MODEL = json.load(open('model.json'))


def load_schema_with_refs_from_path(schema_path: PathLike, proxies=True):
    base_uri = f'{schema_path.parent.as_uri()}/'
    return jsonref.loads(open(schema_path).read(),
                         base_uri=base_uri, proxies=proxies, jsonschema=False)


if __name__ == '__main__':
    schema_path = pathlib.Path(sys.argv[1]).absolute()
    schema_without_refs = json.load(schema_path.open())
    print(json.dumps(schema_without_refs))
    schema_with_refs = load_schema_with_refs_from_path(schema_path,
                                                       proxies=False)
    print(json.dumps(schema_with_refs))
```
[Archive.zip](https://github.com/gazpachoking/jsonref/files/9933767/Archive.zip)

**Comment by gazpachoking** [comment]
Hmm. I'll take a peek

**Comment by gazpachoking** [comment]
Thanks for the report! I think we should be good to go in 1.0.1. It gets a bit confusing trying to handle the recursive data structures, hopefully I haven't missed anything.
