### ISSUE TITLE
Jsonref in conda-forge is obsolete

### ISSUE THREAD

**Issue by abhisek-lpl** [gazpachoking/jsonref#53]
Jsonref in conda-forge is obsolete. It is still at version `0.2`. It would be nice if the conda-forge feedstock gets updated as well.

**Comment by chambbj** [comment]
I've made an attempt to update the feedstock at https://github.com/conda-forge/jsonref-feedstock/pull/11. I'm not familiar with the package, but it looked to be a fairly straightforward update. Maintainers have been notified. 🤞🏼

**Comment by jgunstone** [comment]
looks like it is now up-to-date:
https://prefix.dev/channels/conda-forge/packages/jsonref

**Comment by gazpachoking** [comment]
Awesome, thanks everyone
