### ISSUE TITLE
Use `jsonref/` and directory for the source code

### ISSUE THREAD

**Issue by dostuffthatmatters** [gazpachoking/jsonref#64]
When installing this package, all files are put into `site-packages/` instead of `site-packages/jsonref`:

<img width="446" alt="Screenshot 2024-01-17 at 21 44 31" src="https://github.com/gazpachoking/jsonref/assets/29046316/c10198f2-a6bb-418f-aa7c-9bda74bd0dfc">

This results in the `site-packages/` directory being cluttered. I don't know how pip would resolve it, if another packages has the same filenames.

I can do a tiny PR for that if you want.

Best,
Moritz

**Comment by gazpachoking** [comment]
You mean change from being a module to a package? Or is there some other way that it would be cleaned up in site-packages? Either way I'm good with a PR.
